# Dev version will include time info
# For example: 4.7.2-dev.20220812

name: Publish By Input Version As dev Tag

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "A valid ref(hash/tags/branch) on TypeScript, eg: v4.6.3, main"
        required: true
        default: 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish latest tag
        uses: ./.github/actions/publish-npm
        with:
          distTag: "dev"
          npmToken: ${{ secrets.NPM_TOKEN }}
          ref: ${{ github.event.inputs.ref }}
