name: Release As Latest Tag

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "A valid ref(hash/tags/branch) on TypeScript, eg: v4.6.3, main"
        required: true
        default: 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish latest tag
        uses: ./.github/actions/publish-npm
        with:
          distTag: "latest"
          ref: ${{ github.event.inputs.ref }}
